---

- hosts: all
  become: true
  gather_facts: false
  tasks:

  - name: reboot all servers
    tags: reboot
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot
    wait_for_connection:
      connect_timeout: 10
      sleep: 5
      delay: 5
      timeout: 100

  - name: Check for uptime
    shell: "uptime"
    register: Uptime

  - debug: var=Uptime
